baseurl = "https://karaman.is"
title = "Catherine S Nagawa - Health and Thoughts"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5
#googleAnalytics = ""

# allow html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
		unsafe = true

[author]
    name = "Catherine Nagawa"
	twitter = "https://twitter.com/Katesuubi1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Catherine Nagawa"
    subtitle = "Health and Thoughts"
    keywords = " health thoughts"
    copyright = "© 2020-2021"
    menuMore = "stuff"
    writtenBy = "by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Catherine Nagawa"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
		weight = 4

      [[languages.en.menu.main]]
        identifier = "research"
        name = "research"
        url = "/research"
		weight = 2

      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog"
		weight = 1

      [[languages.en.menu.main]]
        identifier = "thoughts"
        name = "thoughts"
        url = "/artist"

      [[languages.en.menu.main]]
        identifier = "facts"
        name = "facts"
        url = "/street"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "archive"
        url = "/archive"
